// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/grpc/protos/auth_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account Management Messages
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // User-defined account name
	ServerUrl     string                 `protobuf:"bytes,2,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` // Cloudreve server URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Account       *AccountInfo           `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateAccountResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CreateAccountResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{2}
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountInfo         `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccountsResponse) GetAccounts() []*AccountInfo {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Account       *AccountInfo           `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAccountResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetAccountResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAccountResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type SetActiveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveAccountRequest) Reset() {
	*x = SetActiveAccountRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveAccountRequest) ProtoMessage() {}

func (x *SetActiveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveAccountRequest.ProtoReflect.Descriptor instead.
func (*SetActiveAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *SetActiveAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type SetActiveAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveAccountResponse) Reset() {
	*x = SetActiveAccountResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveAccountResponse) ProtoMessage() {}

func (x *SetActiveAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveAccountResponse.ProtoReflect.Descriptor instead.
func (*SetActiveAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{9}
}

func (x *SetActiveAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetActiveAccountResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetActiveAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAccountRequest) Reset() {
	*x = GetActiveAccountRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAccountRequest) ProtoMessage() {}

func (x *GetActiveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAccountRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{10}
}

type GetActiveAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Account       *AccountInfo           `protobuf:"bytes,3,opt,name=account,proto3,oneof" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAccountResponse) Reset() {
	*x = GetActiveAccountResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAccountResponse) ProtoMessage() {}

func (x *GetActiveAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAccountResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetActiveAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetActiveAccountResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetActiveAccountResponse) GetAccount() *AccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServerUrl       string                 `protobuf:"bytes,3,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	IsActive        bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsAuthenticated bool                   `protobuf:"varint,5,opt,name=is_authenticated,json=isAuthenticated,proto3" json:"is_authenticated,omitempty"`
	Email           *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	UserId          *string                `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	LastLoginAt     *string                `protobuf:"bytes,8,opt,name=last_login_at,json=lastLoginAt,proto3,oneof" json:"last_login_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{12}
}

func (x *AccountInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountInfo) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *AccountInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AccountInfo) GetIsAuthenticated() bool {
	if x != nil {
		return x.IsAuthenticated
	}
	return false
}

func (x *AccountInfo) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *AccountInfo) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *AccountInfo) GetLastLoginAt() string {
	if x != nil && x.LastLoginAt != nil {
		return *x.LastLoginAt
	}
	return ""
}

// Authentication Messages
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{13}
}

func (x *LoginRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Login2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login2FARequest) Reset() {
	*x = Login2FARequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login2FARequest) ProtoMessage() {}

func (x *Login2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login2FARequest.ProtoReflect.Descriptor instead.
func (*Login2FARequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{14}
}

func (x *Login2FARequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Login2FARequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	User          *UserInfo              `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{15}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{16}
}

func (x *LogoutRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserInfoRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{19}
}

func (x *UserInfoResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GroupId       int64                  `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	StorageUsed   int64                  `protobuf:"varint,7,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	StorageTotal  int64                  `protobuf:"varint,8,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{20}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UserInfo) GetStorageUsed() int64 {
	if x != nil {
		return x.StorageUsed
	}
	return 0
}

func (x *UserInfo) GetStorageTotal() int64 {
	if x != nil {
		return x.StorageTotal
	}
	return 0
}

type IsAuthenticatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAuthenticatedRequest) Reset() {
	*x = IsAuthenticatedRequest{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAuthenticatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAuthenticatedRequest) ProtoMessage() {}

func (x *IsAuthenticatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAuthenticatedRequest.ProtoReflect.Descriptor instead.
func (*IsAuthenticatedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{21}
}

func (x *IsAuthenticatedRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type IsAuthenticatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authenticated bool                   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAuthenticatedResponse) Reset() {
	*x = IsAuthenticatedResponse{}
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAuthenticatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAuthenticatedResponse) ProtoMessage() {}

func (x *IsAuthenticatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_auth_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAuthenticatedResponse.ProtoReflect.Descriptor instead.
func (*IsAuthenticatedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_auth_service_proto_rawDescGZIP(), []int{22}
}

func (x *IsAuthenticatedResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

var File_pkg_grpc_protos_auth_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_protos_auth_service_proto_rawDesc = "" +
	"\n" +
	"\"pkg/grpc/protos/auth_service.proto\x12\bsyncreve\"I\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"server_url\x18\x02 \x01(\tR\tserverUrl\"\x98\x01\n" +
	"\x15CreateAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x124\n" +
	"\aaccount\x18\x03 \x01(\v2\x15.syncreve.AccountInfoH\x01R\aaccount\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_account\"\x15\n" +
	"\x13ListAccountsRequest\"I\n" +
	"\x14ListAccountsResponse\x121\n" +
	"\baccounts\x18\x01 \x03(\v2\x15.syncreve.AccountInfoR\baccounts\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\x95\x01\n" +
	"\x12GetAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x124\n" +
	"\aaccount\x18\x03 \x01(\v2\x15.syncreve.AccountInfoH\x01R\aaccount\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_account\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"V\n" +
	"\x15DeleteAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"8\n" +
	"\x17SetActiveAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"Y\n" +
	"\x18SetActiveAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x19\n" +
	"\x17GetActiveAccountRequest\"\x9b\x01\n" +
	"\x18GetActiveAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x124\n" +
	"\aaccount\x18\x03 \x01(\v2\x15.syncreve.AccountInfoH\x01R\aaccount\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_account\"\xa2\x02\n" +
	"\vAccountInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"server_url\x18\x03 \x01(\tR\tserverUrl\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12)\n" +
	"\x10is_authenticated\x18\x05 \x01(\bR\x0fisAuthenticated\x12\x19\n" +
	"\x05email\x18\x06 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\a \x01(\tH\x01R\x06userId\x88\x01\x01\x12'\n" +
	"\rlast_login_at\x18\b \x01(\tH\x02R\vlastLoginAt\x88\x01\x01B\b\n" +
	"\x06_emailB\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_last_login_at\"_\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"D\n" +
	"\x0fLogin2FARequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x84\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12+\n" +
	"\x04user\x18\x03 \x01(\v2\x12.syncreve.UserInfoH\x01R\x04user\x88\x01\x01B\b\n" +
	"\x06_errorB\a\n" +
	"\x05_user\".\n" +
	"\rLogoutRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x12GetUserInfoRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\":\n" +
	"\x10UserInfoResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.syncreve.UserInfoR\x04user\"\xe3\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\x03R\agroupId\x12!\n" +
	"\fstorage_used\x18\a \x01(\x03R\vstorageUsed\x12#\n" +
	"\rstorage_total\x18\b \x01(\x03R\fstorageTotal\"7\n" +
	"\x16IsAuthenticatedRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"?\n" +
	"\x17IsAuthenticatedResponse\x12$\n" +
	"\rauthenticated\x18\x01 \x01(\bR\rauthenticated2\xed\x06\n" +
	"\vAuthService\x12R\n" +
	"\rCreateAccount\x12\x1e.syncreve.CreateAccountRequest\x1a\x1f.syncreve.CreateAccountResponse\"\x00\x12O\n" +
	"\fListAccounts\x12\x1d.syncreve.ListAccountsRequest\x1a\x1e.syncreve.ListAccountsResponse\"\x00\x12I\n" +
	"\n" +
	"GetAccount\x12\x1b.syncreve.GetAccountRequest\x1a\x1c.syncreve.GetAccountResponse\"\x00\x12R\n" +
	"\rDeleteAccount\x12\x1e.syncreve.DeleteAccountRequest\x1a\x1f.syncreve.DeleteAccountResponse\"\x00\x12[\n" +
	"\x10SetActiveAccount\x12!.syncreve.SetActiveAccountRequest\x1a\".syncreve.SetActiveAccountResponse\"\x00\x12[\n" +
	"\x10GetActiveAccount\x12!.syncreve.GetActiveAccountRequest\x1a\".syncreve.GetActiveAccountResponse\"\x00\x12:\n" +
	"\x05Login\x12\x16.syncreve.LoginRequest\x1a\x17.syncreve.LoginResponse\"\x00\x12@\n" +
	"\bLogin2FA\x12\x19.syncreve.Login2FARequest\x1a\x17.syncreve.LoginResponse\"\x00\x12=\n" +
	"\x06Logout\x12\x17.syncreve.LogoutRequest\x1a\x18.syncreve.LogoutResponse\"\x00\x12I\n" +
	"\vGetUserInfo\x12\x1c.syncreve.GetUserInfoRequest\x1a\x1a.syncreve.UserInfoResponse\"\x00\x12X\n" +
	"\x0fIsAuthenticated\x12 .syncreve.IsAuthenticatedRequest\x1a!.syncreve.IsAuthenticatedResponse\"\x00B+Z)github.com/xkeyC/Syncreve/pkg/grpc/protosb\x06proto3"

var (
	file_pkg_grpc_protos_auth_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_protos_auth_service_proto_rawDescData []byte
)

func file_pkg_grpc_protos_auth_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protos_auth_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protos_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_auth_service_proto_rawDesc), len(file_pkg_grpc_protos_auth_service_proto_rawDesc)))
	})
	return file_pkg_grpc_protos_auth_service_proto_rawDescData
}

var file_pkg_grpc_protos_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_grpc_protos_auth_service_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),     // 0: syncreve.CreateAccountRequest
	(*CreateAccountResponse)(nil),    // 1: syncreve.CreateAccountResponse
	(*ListAccountsRequest)(nil),      // 2: syncreve.ListAccountsRequest
	(*ListAccountsResponse)(nil),     // 3: syncreve.ListAccountsResponse
	(*GetAccountRequest)(nil),        // 4: syncreve.GetAccountRequest
	(*GetAccountResponse)(nil),       // 5: syncreve.GetAccountResponse
	(*DeleteAccountRequest)(nil),     // 6: syncreve.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),    // 7: syncreve.DeleteAccountResponse
	(*SetActiveAccountRequest)(nil),  // 8: syncreve.SetActiveAccountRequest
	(*SetActiveAccountResponse)(nil), // 9: syncreve.SetActiveAccountResponse
	(*GetActiveAccountRequest)(nil),  // 10: syncreve.GetActiveAccountRequest
	(*GetActiveAccountResponse)(nil), // 11: syncreve.GetActiveAccountResponse
	(*AccountInfo)(nil),              // 12: syncreve.AccountInfo
	(*LoginRequest)(nil),             // 13: syncreve.LoginRequest
	(*Login2FARequest)(nil),          // 14: syncreve.Login2FARequest
	(*LoginResponse)(nil),            // 15: syncreve.LoginResponse
	(*LogoutRequest)(nil),            // 16: syncreve.LogoutRequest
	(*LogoutResponse)(nil),           // 17: syncreve.LogoutResponse
	(*GetUserInfoRequest)(nil),       // 18: syncreve.GetUserInfoRequest
	(*UserInfoResponse)(nil),         // 19: syncreve.UserInfoResponse
	(*UserInfo)(nil),                 // 20: syncreve.UserInfo
	(*IsAuthenticatedRequest)(nil),   // 21: syncreve.IsAuthenticatedRequest
	(*IsAuthenticatedResponse)(nil),  // 22: syncreve.IsAuthenticatedResponse
}
var file_pkg_grpc_protos_auth_service_proto_depIdxs = []int32{
	12, // 0: syncreve.CreateAccountResponse.account:type_name -> syncreve.AccountInfo
	12, // 1: syncreve.ListAccountsResponse.accounts:type_name -> syncreve.AccountInfo
	12, // 2: syncreve.GetAccountResponse.account:type_name -> syncreve.AccountInfo
	12, // 3: syncreve.GetActiveAccountResponse.account:type_name -> syncreve.AccountInfo
	20, // 4: syncreve.LoginResponse.user:type_name -> syncreve.UserInfo
	20, // 5: syncreve.UserInfoResponse.user:type_name -> syncreve.UserInfo
	0,  // 6: syncreve.AuthService.CreateAccount:input_type -> syncreve.CreateAccountRequest
	2,  // 7: syncreve.AuthService.ListAccounts:input_type -> syncreve.ListAccountsRequest
	4,  // 8: syncreve.AuthService.GetAccount:input_type -> syncreve.GetAccountRequest
	6,  // 9: syncreve.AuthService.DeleteAccount:input_type -> syncreve.DeleteAccountRequest
	8,  // 10: syncreve.AuthService.SetActiveAccount:input_type -> syncreve.SetActiveAccountRequest
	10, // 11: syncreve.AuthService.GetActiveAccount:input_type -> syncreve.GetActiveAccountRequest
	13, // 12: syncreve.AuthService.Login:input_type -> syncreve.LoginRequest
	14, // 13: syncreve.AuthService.Login2FA:input_type -> syncreve.Login2FARequest
	16, // 14: syncreve.AuthService.Logout:input_type -> syncreve.LogoutRequest
	18, // 15: syncreve.AuthService.GetUserInfo:input_type -> syncreve.GetUserInfoRequest
	21, // 16: syncreve.AuthService.IsAuthenticated:input_type -> syncreve.IsAuthenticatedRequest
	1,  // 17: syncreve.AuthService.CreateAccount:output_type -> syncreve.CreateAccountResponse
	3,  // 18: syncreve.AuthService.ListAccounts:output_type -> syncreve.ListAccountsResponse
	5,  // 19: syncreve.AuthService.GetAccount:output_type -> syncreve.GetAccountResponse
	7,  // 20: syncreve.AuthService.DeleteAccount:output_type -> syncreve.DeleteAccountResponse
	9,  // 21: syncreve.AuthService.SetActiveAccount:output_type -> syncreve.SetActiveAccountResponse
	11, // 22: syncreve.AuthService.GetActiveAccount:output_type -> syncreve.GetActiveAccountResponse
	15, // 23: syncreve.AuthService.Login:output_type -> syncreve.LoginResponse
	15, // 24: syncreve.AuthService.Login2FA:output_type -> syncreve.LoginResponse
	17, // 25: syncreve.AuthService.Logout:output_type -> syncreve.LogoutResponse
	19, // 26: syncreve.AuthService.GetUserInfo:output_type -> syncreve.UserInfoResponse
	22, // 27: syncreve.AuthService.IsAuthenticated:output_type -> syncreve.IsAuthenticatedResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protos_auth_service_proto_init() }
func file_pkg_grpc_protos_auth_service_proto_init() {
	if File_pkg_grpc_protos_auth_service_proto != nil {
		return
	}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_pkg_grpc_protos_auth_service_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_auth_service_proto_rawDesc), len(file_pkg_grpc_protos_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_protos_auth_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protos_auth_service_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_protos_auth_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protos_auth_service_proto = out.File
	file_pkg_grpc_protos_auth_service_proto_goTypes = nil
	file_pkg_grpc_protos_auth_service_proto_depIdxs = nil
}
