// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/grpc/protos/download_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DownloadService_AddTask_FullMethodName         = "/syncreve.DownloadService/AddTask"
	DownloadService_AddTasksByDir_FullMethodName   = "/syncreve.DownloadService/AddTasksByDir"
	DownloadService_CancelTask_FullMethodName      = "/syncreve.DownloadService/CancelTask"
	DownloadService_GetTaskInfo_FullMethodName     = "/syncreve.DownloadService/GetTaskInfo"
	DownloadService_ListTasks_FullMethodName       = "/syncreve.DownloadService/ListTasks"
	DownloadService_WatchTaskStatus_FullMethodName = "/syncreve.DownloadService/WatchTaskStatus"
	DownloadService_PauseTask_FullMethodName       = "/syncreve.DownloadService/PauseTask"
	DownloadService_ResumeTask_FullMethodName      = "/syncreve.DownloadService/ResumeTask"
	DownloadService_RetryTask_FullMethodName       = "/syncreve.DownloadService/RetryTask"
	DownloadService_ClearCompleted_FullMethodName  = "/syncreve.DownloadService/ClearCompleted"
	DownloadService_GetStats_FullMethodName        = "/syncreve.DownloadService/GetStats"
)

// DownloadServiceClient is the client API for DownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DownloadService provides file download management
type DownloadServiceClient interface {
	// Add download task
	AddTask(ctx context.Context, in *AddDownloadTaskRequest, opts ...grpc.CallOption) (*AddDownloadTaskResponse, error)
	// Add batch download tasks by directory
	AddTasksByDir(ctx context.Context, in *AddDownloadTasksByDirRequest, opts ...grpc.CallOption) (*AddDownloadTaskResponse, error)
	// Cancel download task
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// Get download task info
	GetTaskInfo(ctx context.Context, in *GetTaskInfoRequest, opts ...grpc.CallOption) (*TaskInfoResponse, error)
	// List download tasks
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// Get task status stream
	WatchTaskStatus(ctx context.Context, in *WatchTaskStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskStatusUpdate], error)
	// Pause download task
	PauseTask(ctx context.Context, in *PauseTaskRequest, opts ...grpc.CallOption) (*PauseTaskResponse, error)
	// Resume download task
	ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...grpc.CallOption) (*ResumeTaskResponse, error)
	// Retry failed task
	RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*RetryTaskResponse, error)
	// Clear completed tasks
	ClearCompleted(ctx context.Context, in *ClearCompletedRequest, opts ...grpc.CallOption) (*ClearCompletedResponse, error)
	// Get download statistics
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type downloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadServiceClient(cc grpc.ClientConnInterface) DownloadServiceClient {
	return &downloadServiceClient{cc}
}

func (c *downloadServiceClient) AddTask(ctx context.Context, in *AddDownloadTaskRequest, opts ...grpc.CallOption) (*AddDownloadTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDownloadTaskResponse)
	err := c.cc.Invoke(ctx, DownloadService_AddTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) AddTasksByDir(ctx context.Context, in *AddDownloadTasksByDirRequest, opts ...grpc.CallOption) (*AddDownloadTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDownloadTaskResponse)
	err := c.cc.Invoke(ctx, DownloadService_AddTasksByDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, DownloadService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) GetTaskInfo(ctx context.Context, in *GetTaskInfoRequest, opts ...grpc.CallOption) (*TaskInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskInfoResponse)
	err := c.cc.Invoke(ctx, DownloadService_GetTaskInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, DownloadService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) WatchTaskStatus(ctx context.Context, in *WatchTaskStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DownloadService_ServiceDesc.Streams[0], DownloadService_WatchTaskStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTaskStatusRequest, TaskStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DownloadService_WatchTaskStatusClient = grpc.ServerStreamingClient[TaskStatusUpdate]

func (c *downloadServiceClient) PauseTask(ctx context.Context, in *PauseTaskRequest, opts ...grpc.CallOption) (*PauseTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseTaskResponse)
	err := c.cc.Invoke(ctx, DownloadService_PauseTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) ResumeTask(ctx context.Context, in *ResumeTaskRequest, opts ...grpc.CallOption) (*ResumeTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeTaskResponse)
	err := c.cc.Invoke(ctx, DownloadService_ResumeTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*RetryTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryTaskResponse)
	err := c.cc.Invoke(ctx, DownloadService_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) ClearCompleted(ctx context.Context, in *ClearCompletedRequest, opts ...grpc.CallOption) (*ClearCompletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCompletedResponse)
	err := c.cc.Invoke(ctx, DownloadService_ClearCompleted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, DownloadService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloadServiceServer is the server API for DownloadService service.
// All implementations must embed UnimplementedDownloadServiceServer
// for forward compatibility.
//
// DownloadService provides file download management
type DownloadServiceServer interface {
	// Add download task
	AddTask(context.Context, *AddDownloadTaskRequest) (*AddDownloadTaskResponse, error)
	// Add batch download tasks by directory
	AddTasksByDir(context.Context, *AddDownloadTasksByDirRequest) (*AddDownloadTaskResponse, error)
	// Cancel download task
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// Get download task info
	GetTaskInfo(context.Context, *GetTaskInfoRequest) (*TaskInfoResponse, error)
	// List download tasks
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// Get task status stream
	WatchTaskStatus(*WatchTaskStatusRequest, grpc.ServerStreamingServer[TaskStatusUpdate]) error
	// Pause download task
	PauseTask(context.Context, *PauseTaskRequest) (*PauseTaskResponse, error)
	// Resume download task
	ResumeTask(context.Context, *ResumeTaskRequest) (*ResumeTaskResponse, error)
	// Retry failed task
	RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error)
	// Clear completed tasks
	ClearCompleted(context.Context, *ClearCompletedRequest) (*ClearCompletedResponse, error)
	// Get download statistics
	GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedDownloadServiceServer()
}

// UnimplementedDownloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDownloadServiceServer struct{}

func (UnimplementedDownloadServiceServer) AddTask(context.Context, *AddDownloadTaskRequest) (*AddDownloadTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedDownloadServiceServer) AddTasksByDir(context.Context, *AddDownloadTasksByDirRequest) (*AddDownloadTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTasksByDir not implemented")
}
func (UnimplementedDownloadServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedDownloadServiceServer) GetTaskInfo(context.Context, *GetTaskInfoRequest) (*TaskInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskInfo not implemented")
}
func (UnimplementedDownloadServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedDownloadServiceServer) WatchTaskStatus(*WatchTaskStatusRequest, grpc.ServerStreamingServer[TaskStatusUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method WatchTaskStatus not implemented")
}
func (UnimplementedDownloadServiceServer) PauseTask(context.Context, *PauseTaskRequest) (*PauseTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseTask not implemented")
}
func (UnimplementedDownloadServiceServer) ResumeTask(context.Context, *ResumeTaskRequest) (*ResumeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeTask not implemented")
}
func (UnimplementedDownloadServiceServer) RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedDownloadServiceServer) ClearCompleted(context.Context, *ClearCompletedRequest) (*ClearCompletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearCompleted not implemented")
}
func (UnimplementedDownloadServiceServer) GetStats(context.Context, *GetStatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedDownloadServiceServer) mustEmbedUnimplementedDownloadServiceServer() {}
func (UnimplementedDownloadServiceServer) testEmbeddedByValue()                         {}

// UnsafeDownloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloadServiceServer will
// result in compilation errors.
type UnsafeDownloadServiceServer interface {
	mustEmbedUnimplementedDownloadServiceServer()
}

func RegisterDownloadServiceServer(s grpc.ServiceRegistrar, srv DownloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedDownloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DownloadService_ServiceDesc, srv)
}

func _DownloadService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDownloadTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_AddTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).AddTask(ctx, req.(*AddDownloadTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_AddTasksByDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDownloadTasksByDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).AddTasksByDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_AddTasksByDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).AddTasksByDir(ctx, req.(*AddDownloadTasksByDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_GetTaskInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).GetTaskInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_GetTaskInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).GetTaskInfo(ctx, req.(*GetTaskInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_WatchTaskStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTaskStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownloadServiceServer).WatchTaskStatus(m, &grpc.GenericServerStream[WatchTaskStatusRequest, TaskStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DownloadService_WatchTaskStatusServer = grpc.ServerStreamingServer[TaskStatusUpdate]

func _DownloadService_PauseTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).PauseTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_PauseTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).PauseTask(ctx, req.(*PauseTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_ResumeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).ResumeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_ResumeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).ResumeTask(ctx, req.(*ResumeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).RetryTask(ctx, req.(*RetryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_ClearCompleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCompletedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).ClearCompleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_ClearCompleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).ClearCompleted(ctx, req.(*ClearCompletedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DownloadService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DownloadService_ServiceDesc is the grpc.ServiceDesc for DownloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syncreve.DownloadService",
	HandlerType: (*DownloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _DownloadService_AddTask_Handler,
		},
		{
			MethodName: "AddTasksByDir",
			Handler:    _DownloadService_AddTasksByDir_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _DownloadService_CancelTask_Handler,
		},
		{
			MethodName: "GetTaskInfo",
			Handler:    _DownloadService_GetTaskInfo_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _DownloadService_ListTasks_Handler,
		},
		{
			MethodName: "PauseTask",
			Handler:    _DownloadService_PauseTask_Handler,
		},
		{
			MethodName: "ResumeTask",
			Handler:    _DownloadService_ResumeTask_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _DownloadService_RetryTask_Handler,
		},
		{
			MethodName: "ClearCompleted",
			Handler:    _DownloadService_ClearCompleted_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _DownloadService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTaskStatus",
			Handler:       _DownloadService_WatchTaskStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/grpc/protos/download_service.proto",
}
