// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/grpc/protos/download_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_WAITING     TaskStatus = 0
	TaskStatus_DOWNLOADING TaskStatus = 1
	TaskStatus_PAUSED      TaskStatus = 2
	TaskStatus_COMPLETED   TaskStatus = 3
	TaskStatus_FAILED      TaskStatus = 4
	TaskStatus_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "WAITING",
		1: "DOWNLOADING",
		2: "PAUSED",
		3: "COMPLETED",
		4: "FAILED",
		5: "CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"WAITING":     0,
		"DOWNLOADING": 1,
		"PAUSED":      2,
		"COMPLETED":   3,
		"FAILED":      4,
		"CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_protos_download_service_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_pkg_grpc_protos_download_service_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_NORMAL TaskType = 0
	TaskType_BATCH  TaskType = 1
	TaskType_SYNC   TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "NORMAL",
		1: "BATCH",
		2: "SYNC",
	}
	TaskType_value = map[string]int32{
		"NORMAL": 0,
		"BATCH":  1,
		"SYNC":   2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_protos_download_service_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_pkg_grpc_protos_download_service_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{1}
}

type DownloadTaskInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId      string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FileId         string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName       string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	SavePath       string                 `protobuf:"bytes,5,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	TotalSize      int64                  `protobuf:"varint,6,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	DownloadedSize int64                  `protobuf:"varint,7,opt,name=downloaded_size,json=downloadedSize,proto3" json:"downloaded_size,omitempty"`
	Status         TaskStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=syncreve.TaskStatus" json:"status,omitempty"`
	Type           TaskType               `protobuf:"varint,9,opt,name=type,proto3,enum=syncreve.TaskType" json:"type,omitempty"`
	Error          string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt    *string                `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Speed          *float64               `protobuf:"fixed64,14,opt,name=speed,proto3,oneof" json:"speed,omitempty"`       // bytes per second
	Progress       *float64               `protobuf:"fixed64,15,opt,name=progress,proto3,oneof" json:"progress,omitempty"` // 0-100
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadTaskInfo) Reset() {
	*x = DownloadTaskInfo{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTaskInfo) ProtoMessage() {}

func (x *DownloadTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTaskInfo.ProtoReflect.Descriptor instead.
func (*DownloadTaskInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadTaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadTaskInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DownloadTaskInfo) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadTaskInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadTaskInfo) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *DownloadTaskInfo) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *DownloadTaskInfo) GetDownloadedSize() int64 {
	if x != nil {
		return x.DownloadedSize
	}
	return 0
}

func (x *DownloadTaskInfo) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_WAITING
}

func (x *DownloadTaskInfo) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_NORMAL
}

func (x *DownloadTaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DownloadTaskInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DownloadTaskInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DownloadTaskInfo) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

func (x *DownloadTaskInfo) GetSpeed() float64 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *DownloadTaskInfo) GetProgress() float64 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

type AddDownloadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Files         []*FileToDownload      `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	SavePath      string                 `protobuf:"bytes,3,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Type          TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=syncreve.TaskType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDownloadTaskRequest) Reset() {
	*x = AddDownloadTaskRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDownloadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDownloadTaskRequest) ProtoMessage() {}

func (x *AddDownloadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDownloadTaskRequest.ProtoReflect.Descriptor instead.
func (*AddDownloadTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddDownloadTaskRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddDownloadTaskRequest) GetFiles() []*FileToDownload {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AddDownloadTaskRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *AddDownloadTaskRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_NORMAL
}

type FileToDownload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Uri           *string                `protobuf:"bytes,3,opt,name=uri,proto3,oneof" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileToDownload) Reset() {
	*x = FileToDownload{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileToDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileToDownload) ProtoMessage() {}

func (x *FileToDownload) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileToDownload.ProtoReflect.Descriptor instead.
func (*FileToDownload) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{2}
}

func (x *FileToDownload) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileToDownload) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileToDownload) GetUri() string {
	if x != nil && x.Uri != nil {
		return *x.Uri
	}
	return ""
}

type AddDownloadTasksByDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DirPath       string                 `protobuf:"bytes,2,opt,name=dir_path,json=dirPath,proto3" json:"dir_path,omitempty"`
	SavePath      string                 `protobuf:"bytes,3,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	Type          TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=syncreve.TaskType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDownloadTasksByDirRequest) Reset() {
	*x = AddDownloadTasksByDirRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDownloadTasksByDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDownloadTasksByDirRequest) ProtoMessage() {}

func (x *AddDownloadTasksByDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDownloadTasksByDirRequest.ProtoReflect.Descriptor instead.
func (*AddDownloadTasksByDirRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{3}
}

func (x *AddDownloadTasksByDirRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddDownloadTasksByDirRequest) GetDirPath() string {
	if x != nil {
		return x.DirPath
	}
	return ""
}

func (x *AddDownloadTasksByDirRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *AddDownloadTasksByDirRequest) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_NORMAL
}

type AddDownloadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDownloadTaskResponse) Reset() {
	*x = AddDownloadTaskResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDownloadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDownloadTaskResponse) ProtoMessage() {}

func (x *AddDownloadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDownloadTaskResponse.ProtoReflect.Descriptor instead.
func (*AddDownloadTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddDownloadTaskResponse) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetTaskInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskInfoRequest) Reset() {
	*x = GetTaskInfoRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskInfoRequest) ProtoMessage() {}

func (x *GetTaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskInfoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *DownloadTaskInfo      `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoResponse) Reset() {
	*x = TaskInfoResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoResponse) ProtoMessage() {}

func (x *TaskInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoResponse.ProtoReflect.Descriptor instead.
func (*TaskInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{8}
}

func (x *TaskInfoResponse) GetTask() *DownloadTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        *TaskStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=syncreve.TaskStatus,oneof" json:"status,omitempty"`
	Type          *TaskType              `protobuf:"varint,3,opt,name=type,proto3,enum=syncreve.TaskType,oneof" json:"type,omitempty"`
	Page          *int32                 `protobuf:"varint,4,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PerPage       *int32                 `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3,oneof" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTasksRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TaskStatus_WAITING
}

func (x *ListTasksRequest) GetType() TaskType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TaskType_NORMAL
}

func (x *ListTasksRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListTasksRequest) GetPerPage() int32 {
	if x != nil && x.PerPage != nil {
		return *x.PerPage
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*DownloadTaskInfo    `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListTasksResponse) GetTasks() []*DownloadTaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WatchTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"` // If not set, watch all tasks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskStatusRequest) Reset() {
	*x = WatchTaskStatusRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskStatusRequest) ProtoMessage() {}

func (x *WatchTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{11}
}

func (x *WatchTaskStatusRequest) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

type TaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *DownloadTaskInfo      `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusUpdate) Reset() {
	*x = TaskStatusUpdate{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusUpdate) ProtoMessage() {}

func (x *TaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*TaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{12}
}

func (x *TaskStatusUpdate) GetTask() *DownloadTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type PauseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTaskRequest) Reset() {
	*x = PauseTaskRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTaskRequest) ProtoMessage() {}

func (x *PauseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTaskRequest.ProtoReflect.Descriptor instead.
func (*PauseTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{13}
}

func (x *PauseTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PauseTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTaskResponse) Reset() {
	*x = PauseTaskResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTaskResponse) ProtoMessage() {}

func (x *PauseTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTaskResponse.ProtoReflect.Descriptor instead.
func (*PauseTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{14}
}

func (x *PauseTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResumeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTaskRequest) Reset() {
	*x = ResumeTaskRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskRequest) ProtoMessage() {}

func (x *ResumeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ResumeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTaskResponse) Reset() {
	*x = ResumeTaskResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskResponse) ProtoMessage() {}

func (x *ResumeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskResponse.ProtoReflect.Descriptor instead.
func (*ResumeTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetryTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskRequest) Reset() {
	*x = RetryTaskRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRequest) ProtoMessage() {}

func (x *RetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{17}
}

func (x *RetryTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RetryTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewTaskId     *string                `protobuf:"bytes,2,opt,name=new_task_id,json=newTaskId,proto3,oneof" json:"new_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskResponse) Reset() {
	*x = RetryTaskResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskResponse) ProtoMessage() {}

func (x *RetryTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{18}
}

func (x *RetryTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryTaskResponse) GetNewTaskId() string {
	if x != nil && x.NewTaskId != nil {
		return *x.NewTaskId
	}
	return ""
}

type ClearCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCompletedRequest) Reset() {
	*x = ClearCompletedRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCompletedRequest) ProtoMessage() {}

func (x *ClearCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCompletedRequest.ProtoReflect.Descriptor instead.
func (*ClearCompletedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{19}
}

func (x *ClearCompletedRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ClearCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearedCount  int32                  `protobuf:"varint,1,opt,name=cleared_count,json=clearedCount,proto3" json:"cleared_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCompletedResponse) Reset() {
	*x = ClearCompletedResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCompletedResponse) ProtoMessage() {}

func (x *ClearCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCompletedResponse.ProtoReflect.Descriptor instead.
func (*ClearCompletedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{20}
}

func (x *ClearCompletedResponse) GetClearedCount() int32 {
	if x != nil {
		return x.ClearedCount
	}
	return 0
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type StatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks          int64                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	WaitingTasks        int64                  `protobuf:"varint,2,opt,name=waiting_tasks,json=waitingTasks,proto3" json:"waiting_tasks,omitempty"`
	DownloadingTasks    int64                  `protobuf:"varint,3,opt,name=downloading_tasks,json=downloadingTasks,proto3" json:"downloading_tasks,omitempty"`
	CompletedTasks      int64                  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	FailedTasks         int64                  `protobuf:"varint,5,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	TotalDownloadedSize float64                `protobuf:"fixed64,6,opt,name=total_downloaded_size,json=totalDownloadedSize,proto3" json:"total_downloaded_size,omitempty"`
	CurrentSpeed        float64                `protobuf:"fixed64,7,opt,name=current_speed,json=currentSpeed,proto3" json:"current_speed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_download_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_download_service_proto_rawDescGZIP(), []int{22}
}

func (x *StatsResponse) GetTotalTasks() int64 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *StatsResponse) GetWaitingTasks() int64 {
	if x != nil {
		return x.WaitingTasks
	}
	return 0
}

func (x *StatsResponse) GetDownloadingTasks() int64 {
	if x != nil {
		return x.DownloadingTasks
	}
	return 0
}

func (x *StatsResponse) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *StatsResponse) GetFailedTasks() int64 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *StatsResponse) GetTotalDownloadedSize() float64 {
	if x != nil {
		return x.TotalDownloadedSize
	}
	return 0
}

func (x *StatsResponse) GetCurrentSpeed() float64 {
	if x != nil {
		return x.CurrentSpeed
	}
	return 0
}

var File_pkg_grpc_protos_download_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_protos_download_service_proto_rawDesc = "" +
	"\n" +
	"&pkg/grpc/protos/download_service.proto\x12\bsyncreve\"\x92\x04\n" +
	"\x10DownloadTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1b\n" +
	"\tsave_path\x18\x05 \x01(\tR\bsavePath\x12\x1d\n" +
	"\n" +
	"total_size\x18\x06 \x01(\x03R\ttotalSize\x12'\n" +
	"\x0fdownloaded_size\x18\a \x01(\x03R\x0edownloadedSize\x12,\n" +
	"\x06status\x18\b \x01(\x0e2\x14.syncreve.TaskStatusR\x06status\x12&\n" +
	"\x04type\x18\t \x01(\x0e2\x12.syncreve.TaskTypeR\x04type\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12&\n" +
	"\fcompleted_at\x18\r \x01(\tH\x00R\vcompletedAt\x88\x01\x01\x12\x19\n" +
	"\x05speed\x18\x0e \x01(\x01H\x01R\x05speed\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x0f \x01(\x01H\x02R\bprogress\x88\x01\x01B\x0f\n" +
	"\r_completed_atB\b\n" +
	"\x06_speedB\v\n" +
	"\t_progress\"\xac\x01\n" +
	"\x16AddDownloadTaskRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12.\n" +
	"\x05files\x18\x02 \x03(\v2\x18.syncreve.FileToDownloadR\x05files\x12\x1b\n" +
	"\tsave_path\x18\x03 \x01(\tR\bsavePath\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.syncreve.TaskTypeR\x04type\"e\n" +
	"\x0eFileToDownload\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x15\n" +
	"\x03uri\x18\x03 \x01(\tH\x00R\x03uri\x88\x01\x01B\x06\n" +
	"\x04_uri\"\x9d\x01\n" +
	"\x1cAddDownloadTasksByDirRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bdir_path\x18\x02 \x01(\tR\adirPath\x12\x1b\n" +
	"\tsave_path\x18\x03 \x01(\tR\bsavePath\x12&\n" +
	"\x04type\x18\x04 \x01(\x0e2\x12.syncreve.TaskTypeR\x04type\"4\n" +
	"\x17AddDownloadTaskResponse\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"S\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"-\n" +
	"\x12GetTaskInfoRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"B\n" +
	"\x10TaskInfoResponse\x12.\n" +
	"\x04task\x18\x01 \x01(\v2\x1a.syncreve.DownloadTaskInfoR\x04task\"\xf4\x01\n" +
	"\x10ListTasksRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.syncreve.TaskStatusH\x00R\x06status\x88\x01\x01\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.syncreve.TaskTypeH\x01R\x04type\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x04 \x01(\x05H\x02R\x04page\x88\x01\x01\x12\x1e\n" +
	"\bper_page\x18\x05 \x01(\x05H\x03R\aperPage\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_typeB\a\n" +
	"\x05_pageB\v\n" +
	"\t_per_page\"[\n" +
	"\x11ListTasksResponse\x120\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1a.syncreve.DownloadTaskInfoR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"B\n" +
	"\x16WatchTaskStatusRequest\x12\x1c\n" +
	"\atask_id\x18\x01 \x01(\tH\x00R\x06taskId\x88\x01\x01B\n" +
	"\n" +
	"\b_task_id\"B\n" +
	"\x10TaskStatusUpdate\x12.\n" +
	"\x04task\x18\x01 \x01(\v2\x1a.syncreve.DownloadTaskInfoR\x04task\"+\n" +
	"\x10PauseTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"-\n" +
	"\x11PauseTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11ResumeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x12ResumeTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10RetryTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"b\n" +
	"\x11RetryTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\vnew_task_id\x18\x02 \x01(\tH\x00R\tnewTaskId\x88\x01\x01B\x0e\n" +
	"\f_new_task_id\"6\n" +
	"\x15ClearCompletedRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"=\n" +
	"\x16ClearCompletedResponse\x12#\n" +
	"\rcleared_count\x18\x01 \x01(\x05R\fclearedCount\"0\n" +
	"\x0fGetStatsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xa7\x02\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x03R\n" +
	"totalTasks\x12#\n" +
	"\rwaiting_tasks\x18\x02 \x01(\x03R\fwaitingTasks\x12+\n" +
	"\x11downloading_tasks\x18\x03 \x01(\x03R\x10downloadingTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x04 \x01(\x03R\x0ecompletedTasks\x12!\n" +
	"\ffailed_tasks\x18\x05 \x01(\x03R\vfailedTasks\x122\n" +
	"\x15total_downloaded_size\x18\x06 \x01(\x01R\x13totalDownloadedSize\x12#\n" +
	"\rcurrent_speed\x18\a \x01(\x01R\fcurrentSpeed*`\n" +
	"\n" +
	"TaskStatus\x12\v\n" +
	"\aWAITING\x10\x00\x12\x0f\n" +
	"\vDOWNLOADING\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05*+\n" +
	"\bTaskType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\t\n" +
	"\x05BATCH\x10\x01\x12\b\n" +
	"\x04SYNC\x10\x022\xe8\x06\n" +
	"\x0fDownloadService\x12P\n" +
	"\aAddTask\x12 .syncreve.AddDownloadTaskRequest\x1a!.syncreve.AddDownloadTaskResponse\"\x00\x12\\\n" +
	"\rAddTasksByDir\x12&.syncreve.AddDownloadTasksByDirRequest\x1a!.syncreve.AddDownloadTaskResponse\"\x00\x12I\n" +
	"\n" +
	"CancelTask\x12\x1b.syncreve.CancelTaskRequest\x1a\x1c.syncreve.CancelTaskResponse\"\x00\x12I\n" +
	"\vGetTaskInfo\x12\x1c.syncreve.GetTaskInfoRequest\x1a\x1a.syncreve.TaskInfoResponse\"\x00\x12F\n" +
	"\tListTasks\x12\x1a.syncreve.ListTasksRequest\x1a\x1b.syncreve.ListTasksResponse\"\x00\x12S\n" +
	"\x0fWatchTaskStatus\x12 .syncreve.WatchTaskStatusRequest\x1a\x1a.syncreve.TaskStatusUpdate\"\x000\x01\x12F\n" +
	"\tPauseTask\x12\x1a.syncreve.PauseTaskRequest\x1a\x1b.syncreve.PauseTaskResponse\"\x00\x12I\n" +
	"\n" +
	"ResumeTask\x12\x1b.syncreve.ResumeTaskRequest\x1a\x1c.syncreve.ResumeTaskResponse\"\x00\x12F\n" +
	"\tRetryTask\x12\x1a.syncreve.RetryTaskRequest\x1a\x1b.syncreve.RetryTaskResponse\"\x00\x12U\n" +
	"\x0eClearCompleted\x12\x1f.syncreve.ClearCompletedRequest\x1a .syncreve.ClearCompletedResponse\"\x00\x12@\n" +
	"\bGetStats\x12\x19.syncreve.GetStatsRequest\x1a\x17.syncreve.StatsResponse\"\x00B+Z)github.com/xkeyC/Syncreve/pkg/grpc/protosb\x06proto3"

var (
	file_pkg_grpc_protos_download_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_protos_download_service_proto_rawDescData []byte
)

func file_pkg_grpc_protos_download_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protos_download_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protos_download_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_download_service_proto_rawDesc), len(file_pkg_grpc_protos_download_service_proto_rawDesc)))
	})
	return file_pkg_grpc_protos_download_service_proto_rawDescData
}

var file_pkg_grpc_protos_download_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_grpc_protos_download_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_grpc_protos_download_service_proto_goTypes = []any{
	(TaskStatus)(0),                      // 0: syncreve.TaskStatus
	(TaskType)(0),                        // 1: syncreve.TaskType
	(*DownloadTaskInfo)(nil),             // 2: syncreve.DownloadTaskInfo
	(*AddDownloadTaskRequest)(nil),       // 3: syncreve.AddDownloadTaskRequest
	(*FileToDownload)(nil),               // 4: syncreve.FileToDownload
	(*AddDownloadTasksByDirRequest)(nil), // 5: syncreve.AddDownloadTasksByDirRequest
	(*AddDownloadTaskResponse)(nil),      // 6: syncreve.AddDownloadTaskResponse
	(*CancelTaskRequest)(nil),            // 7: syncreve.CancelTaskRequest
	(*CancelTaskResponse)(nil),           // 8: syncreve.CancelTaskResponse
	(*GetTaskInfoRequest)(nil),           // 9: syncreve.GetTaskInfoRequest
	(*TaskInfoResponse)(nil),             // 10: syncreve.TaskInfoResponse
	(*ListTasksRequest)(nil),             // 11: syncreve.ListTasksRequest
	(*ListTasksResponse)(nil),            // 12: syncreve.ListTasksResponse
	(*WatchTaskStatusRequest)(nil),       // 13: syncreve.WatchTaskStatusRequest
	(*TaskStatusUpdate)(nil),             // 14: syncreve.TaskStatusUpdate
	(*PauseTaskRequest)(nil),             // 15: syncreve.PauseTaskRequest
	(*PauseTaskResponse)(nil),            // 16: syncreve.PauseTaskResponse
	(*ResumeTaskRequest)(nil),            // 17: syncreve.ResumeTaskRequest
	(*ResumeTaskResponse)(nil),           // 18: syncreve.ResumeTaskResponse
	(*RetryTaskRequest)(nil),             // 19: syncreve.RetryTaskRequest
	(*RetryTaskResponse)(nil),            // 20: syncreve.RetryTaskResponse
	(*ClearCompletedRequest)(nil),        // 21: syncreve.ClearCompletedRequest
	(*ClearCompletedResponse)(nil),       // 22: syncreve.ClearCompletedResponse
	(*GetStatsRequest)(nil),              // 23: syncreve.GetStatsRequest
	(*StatsResponse)(nil),                // 24: syncreve.StatsResponse
}
var file_pkg_grpc_protos_download_service_proto_depIdxs = []int32{
	0,  // 0: syncreve.DownloadTaskInfo.status:type_name -> syncreve.TaskStatus
	1,  // 1: syncreve.DownloadTaskInfo.type:type_name -> syncreve.TaskType
	4,  // 2: syncreve.AddDownloadTaskRequest.files:type_name -> syncreve.FileToDownload
	1,  // 3: syncreve.AddDownloadTaskRequest.type:type_name -> syncreve.TaskType
	1,  // 4: syncreve.AddDownloadTasksByDirRequest.type:type_name -> syncreve.TaskType
	2,  // 5: syncreve.TaskInfoResponse.task:type_name -> syncreve.DownloadTaskInfo
	0,  // 6: syncreve.ListTasksRequest.status:type_name -> syncreve.TaskStatus
	1,  // 7: syncreve.ListTasksRequest.type:type_name -> syncreve.TaskType
	2,  // 8: syncreve.ListTasksResponse.tasks:type_name -> syncreve.DownloadTaskInfo
	2,  // 9: syncreve.TaskStatusUpdate.task:type_name -> syncreve.DownloadTaskInfo
	3,  // 10: syncreve.DownloadService.AddTask:input_type -> syncreve.AddDownloadTaskRequest
	5,  // 11: syncreve.DownloadService.AddTasksByDir:input_type -> syncreve.AddDownloadTasksByDirRequest
	7,  // 12: syncreve.DownloadService.CancelTask:input_type -> syncreve.CancelTaskRequest
	9,  // 13: syncreve.DownloadService.GetTaskInfo:input_type -> syncreve.GetTaskInfoRequest
	11, // 14: syncreve.DownloadService.ListTasks:input_type -> syncreve.ListTasksRequest
	13, // 15: syncreve.DownloadService.WatchTaskStatus:input_type -> syncreve.WatchTaskStatusRequest
	15, // 16: syncreve.DownloadService.PauseTask:input_type -> syncreve.PauseTaskRequest
	17, // 17: syncreve.DownloadService.ResumeTask:input_type -> syncreve.ResumeTaskRequest
	19, // 18: syncreve.DownloadService.RetryTask:input_type -> syncreve.RetryTaskRequest
	21, // 19: syncreve.DownloadService.ClearCompleted:input_type -> syncreve.ClearCompletedRequest
	23, // 20: syncreve.DownloadService.GetStats:input_type -> syncreve.GetStatsRequest
	6,  // 21: syncreve.DownloadService.AddTask:output_type -> syncreve.AddDownloadTaskResponse
	6,  // 22: syncreve.DownloadService.AddTasksByDir:output_type -> syncreve.AddDownloadTaskResponse
	8,  // 23: syncreve.DownloadService.CancelTask:output_type -> syncreve.CancelTaskResponse
	10, // 24: syncreve.DownloadService.GetTaskInfo:output_type -> syncreve.TaskInfoResponse
	12, // 25: syncreve.DownloadService.ListTasks:output_type -> syncreve.ListTasksResponse
	14, // 26: syncreve.DownloadService.WatchTaskStatus:output_type -> syncreve.TaskStatusUpdate
	16, // 27: syncreve.DownloadService.PauseTask:output_type -> syncreve.PauseTaskResponse
	18, // 28: syncreve.DownloadService.ResumeTask:output_type -> syncreve.ResumeTaskResponse
	20, // 29: syncreve.DownloadService.RetryTask:output_type -> syncreve.RetryTaskResponse
	22, // 30: syncreve.DownloadService.ClearCompleted:output_type -> syncreve.ClearCompletedResponse
	24, // 31: syncreve.DownloadService.GetStats:output_type -> syncreve.StatsResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protos_download_service_proto_init() }
func file_pkg_grpc_protos_download_service_proto_init() {
	if File_pkg_grpc_protos_download_service_proto != nil {
		return
	}
	file_pkg_grpc_protos_download_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_grpc_protos_download_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_grpc_protos_download_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_grpc_protos_download_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_pkg_grpc_protos_download_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_pkg_grpc_protos_download_service_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_download_service_proto_rawDesc), len(file_pkg_grpc_protos_download_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_protos_download_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protos_download_service_proto_depIdxs,
		EnumInfos:         file_pkg_grpc_protos_download_service_proto_enumTypes,
		MessageInfos:      file_pkg_grpc_protos_download_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protos_download_service_proto = out.File
	file_pkg_grpc_protos_download_service_proto_goTypes = nil
	file_pkg_grpc_protos_download_service_proto_depIdxs = nil
}
