// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/grpc/protos/file_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFilesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccountId          string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Path               string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Page               *int32                 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PerPage            *int32                 `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3,oneof" json:"per_page,omitempty"`
	OrderBy            *string                `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	OrderDirectionDesc *bool                  `protobuf:"varint,6,opt,name=order_direction_desc,json=orderDirectionDesc,proto3,oneof" json:"order_direction_desc,omitempty"`
	Keywords           *string                `protobuf:"bytes,7,opt,name=keywords,proto3,oneof" json:"keywords,omitempty"`
	Refresh            *bool                  `protobuf:"varint,8,opt,name=refresh,proto3,oneof" json:"refresh,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListFilesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListFilesRequest) GetPerPage() int32 {
	if x != nil && x.PerPage != nil {
		return *x.PerPage
	}
	return 0
}

func (x *ListFilesRequest) GetOrderBy() string {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return ""
}

func (x *ListFilesRequest) GetOrderDirectionDesc() bool {
	if x != nil && x.OrderDirectionDesc != nil {
		return *x.OrderDirectionDesc
	}
	return false
}

func (x *ListFilesRequest) GetKeywords() string {
	if x != nil && x.Keywords != nil {
		return *x.Keywords
	}
	return ""
}

func (x *ListFilesRequest) GetRefresh() bool {
	if x != nil && x.Refresh != nil {
		return *x.Refresh
	}
	return false
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ParentPath    string                 `protobuf:"bytes,4,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFilesResponse) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListFilesResponse) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // "file" or "dir"
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SourceUrl     *string                `protobuf:"bytes,8,opt,name=source_url,json=sourceUrl,proto3,oneof" json:"source_url,omitempty"`
	SourceEnabled *int32                 `protobuf:"varint,9,opt,name=source_enabled,json=sourceEnabled,proto3,oneof" json:"source_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{2}
}

func (x *FileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FileInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FileInfo) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

func (x *FileInfo) GetSourceEnabled() int32 {
	if x != nil && x.SourceEnabled != nil {
		return *x.SourceEnabled
	}
	return 0
}

type GetFileInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	TraceRoot     *bool                  `protobuf:"varint,3,opt,name=trace_root,json=traceRoot,proto3,oneof" json:"trace_root,omitempty"`
	IsFolder      *bool                  `protobuf:"varint,4,opt,name=is_folder,json=isFolder,proto3,oneof" json:"is_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileInfoRequest) Reset() {
	*x = GetFileInfoRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileInfoRequest) ProtoMessage() {}

func (x *GetFileInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileInfoRequest.ProtoReflect.Descriptor instead.
func (*GetFileInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileInfoRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetFileInfoRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GetFileInfoRequest) GetTraceRoot() bool {
	if x != nil && x.TraceRoot != nil {
		return *x.TraceRoot
	}
	return false
}

func (x *GetFileInfoRequest) GetIsFolder() bool {
	if x != nil && x.IsFolder != nil {
		return *x.IsFolder
	}
	return false
}

type FileInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfoResponse) Reset() {
	*x = FileInfoResponse{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoResponse) ProtoMessage() {}

func (x *FileInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoResponse.ProtoReflect.Descriptor instead.
func (*FileInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{4}
}

func (x *FileInfoResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "file" or "dir"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFileRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFileRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uris          []string               `protobuf:"bytes,2,rep,name=uris,proto3" json:"uris,omitempty"`
	Force         *bool                  `protobuf:"varint,3,opt,name=force,proto3,oneof" json:"force,omitempty"`
	Unlink        *bool                  `protobuf:"varint,4,opt,name=unlink,proto3,oneof" json:"unlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilesRequest) Reset() {
	*x = DeleteFilesRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilesRequest) ProtoMessage() {}

func (x *DeleteFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilesRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFilesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeleteFilesRequest) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

func (x *DeleteFilesRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *DeleteFilesRequest) GetUnlink() bool {
	if x != nil && x.Unlink != nil {
		return *x.Unlink
	}
	return false
}

type DeleteFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFilesResponse) Reset() {
	*x = DeleteFilesResponse{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilesResponse) ProtoMessage() {}

func (x *DeleteFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilesResponse.ProtoReflect.Descriptor instead.
func (*DeleteFilesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFilesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{8}
}

func (x *RenameFileRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RenameFileRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RenameFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type MoveFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SrcUris       []string               `protobuf:"bytes,2,rep,name=src_uris,json=srcUris,proto3" json:"src_uris,omitempty"`
	DstPath       string                 `protobuf:"bytes,3,opt,name=dst_path,json=dstPath,proto3" json:"dst_path,omitempty"`
	Overwrite     *bool                  `protobuf:"varint,4,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFilesRequest) Reset() {
	*x = MoveFilesRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFilesRequest) ProtoMessage() {}

func (x *MoveFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFilesRequest.ProtoReflect.Descriptor instead.
func (*MoveFilesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{9}
}

func (x *MoveFilesRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MoveFilesRequest) GetSrcUris() []string {
	if x != nil {
		return x.SrcUris
	}
	return nil
}

func (x *MoveFilesRequest) GetDstPath() string {
	if x != nil {
		return x.DstPath
	}
	return ""
}

func (x *MoveFilesRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

type MoveFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFilesResponse) Reset() {
	*x = MoveFilesResponse{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFilesResponse) ProtoMessage() {}

func (x *MoveFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFilesResponse.ProtoReflect.Descriptor instead.
func (*MoveFilesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{10}
}

func (x *MoveFilesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetFileURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Download      *bool                  `protobuf:"varint,3,opt,name=download,proto3,oneof" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileURLRequest) Reset() {
	*x = GetFileURLRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileURLRequest) ProtoMessage() {}

func (x *GetFileURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileURLRequest.ProtoReflect.Descriptor instead.
func (*GetFileURLRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetFileURLRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetFileURLRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GetFileURLRequest) GetDownload() bool {
	if x != nil && x.Download != nil {
		return *x.Download
	}
	return false
}

type FileURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileURLResponse) Reset() {
	*x = FileURLResponse{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileURLResponse) ProtoMessage() {}

func (x *FileURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileURLResponse.ProtoReflect.Descriptor instead.
func (*FileURLResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{12}
}

func (x *FileURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileURLResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GetDirectLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Uris          []string               `protobuf:"bytes,2,rep,name=uris,proto3" json:"uris,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectLinkRequest) Reset() {
	*x = GetDirectLinkRequest{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectLinkRequest) ProtoMessage() {}

func (x *GetDirectLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectLinkRequest.ProtoReflect.Descriptor instead.
func (*GetDirectLinkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetDirectLinkRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetDirectLinkRequest) GetUris() []string {
	if x != nil {
		return x.Uris
	}
	return nil
}

type DirectLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*DirectLink          `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectLinkResponse) Reset() {
	*x = DirectLinkResponse{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectLinkResponse) ProtoMessage() {}

func (x *DirectLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectLinkResponse.ProtoReflect.Descriptor instead.
func (*DirectLinkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{14}
}

func (x *DirectLinkResponse) GetLinks() []*DirectLink {
	if x != nil {
		return x.Links
	}
	return nil
}

type DirectLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Views         int64                  `protobuf:"varint,6,opt,name=views,proto3" json:"views,omitempty"`
	Downloads     int64                  `protobuf:"varint,7,opt,name=downloads,proto3" json:"downloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectLink) Reset() {
	*x = DirectLink{}
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectLink) ProtoMessage() {}

func (x *DirectLink) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectLink.ProtoReflect.Descriptor instead.
func (*DirectLink) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_file_service_proto_rawDescGZIP(), []int{15}
}

func (x *DirectLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DirectLink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectLink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DirectLink) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DirectLink) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DirectLink) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *DirectLink) GetDownloads() int64 {
	if x != nil {
		return x.Downloads
	}
	return 0
}

var File_pkg_grpc_protos_file_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_protos_file_service_proto_rawDesc = "" +
	"\n" +
	"\"pkg/grpc/protos/file_service.proto\x12\bsyncreve\"\xea\x02\n" +
	"\x10ListFilesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05H\x00R\x04page\x88\x01\x01\x12\x1e\n" +
	"\bper_page\x18\x04 \x01(\x05H\x01R\aperPage\x88\x01\x01\x12\x1e\n" +
	"\border_by\x18\x05 \x01(\tH\x02R\aorderBy\x88\x01\x01\x125\n" +
	"\x14order_direction_desc\x18\x06 \x01(\bH\x03R\x12orderDirectionDesc\x88\x01\x01\x12\x1f\n" +
	"\bkeywords\x18\a \x01(\tH\x04R\bkeywords\x88\x01\x01\x12\x1d\n" +
	"\arefresh\x18\b \x01(\bH\x05R\arefresh\x88\x01\x01B\a\n" +
	"\x05_pageB\v\n" +
	"\t_per_pageB\v\n" +
	"\t_order_byB\x17\n" +
	"\x15_order_direction_descB\v\n" +
	"\t_keywordsB\n" +
	"\n" +
	"\b_refresh\"\x91\x01\n" +
	"\x11ListFilesResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.syncreve.FileInfoR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x1f\n" +
	"\vparent_path\x18\x04 \x01(\tR\n" +
	"parentPath\"\x9a\x02\n" +
	"\bFileInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"source_url\x18\b \x01(\tH\x00R\tsourceUrl\x88\x01\x01\x12*\n" +
	"\x0esource_enabled\x18\t \x01(\x05H\x01R\rsourceEnabled\x88\x01\x01B\r\n" +
	"\v_source_urlB\x11\n" +
	"\x0f_source_enabled\"\xa8\x01\n" +
	"\x12GetFileInfoRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\"\n" +
	"\n" +
	"trace_root\x18\x03 \x01(\bH\x00R\ttraceRoot\x88\x01\x01\x12 \n" +
	"\tis_folder\x18\x04 \x01(\bH\x01R\bisFolder\x88\x01\x01B\r\n" +
	"\v_trace_rootB\f\n" +
	"\n" +
	"_is_folder\":\n" +
	"\x10FileInfoResponse\x12&\n" +
	"\x04file\x18\x01 \x01(\v2\x12.syncreve.FileInfoR\x04file\"n\n" +
	"\x11CreateFileRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\x94\x01\n" +
	"\x12DeleteFilesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04uris\x18\x02 \x03(\tR\x04uris\x12\x19\n" +
	"\x05force\x18\x03 \x01(\bH\x00R\x05force\x88\x01\x01\x12\x1b\n" +
	"\x06unlink\x18\x04 \x01(\bH\x01R\x06unlink\x88\x01\x01B\b\n" +
	"\x06_forceB\t\n" +
	"\a_unlink\"+\n" +
	"\x13DeleteFilesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"_\n" +
	"\x11RenameFileRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"\x98\x01\n" +
	"\x10MoveFilesRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bsrc_uris\x18\x02 \x03(\tR\asrcUris\x12\x19\n" +
	"\bdst_path\x18\x03 \x01(\tR\adstPath\x12!\n" +
	"\toverwrite\x18\x04 \x01(\bH\x00R\toverwrite\x88\x01\x01B\f\n" +
	"\n" +
	"_overwrite\")\n" +
	"\x11MoveFilesResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"r\n" +
	"\x11GetFileURLRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x1f\n" +
	"\bdownload\x18\x03 \x01(\bH\x00R\bdownload\x88\x01\x01B\v\n" +
	"\t_download\"E\n" +
	"\x0fFileURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"I\n" +
	"\x14GetDirectLinkRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04uris\x18\x02 \x03(\tR\x04uris\"@\n" +
	"\x12DirectLinkResponse\x12*\n" +
	"\x05links\x18\x01 \x03(\v2\x14.syncreve.DirectLinkR\x05links\"\xb5\x01\n" +
	"\n" +
	"DirectLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05views\x18\x06 \x01(\x03R\x05views\x12\x1c\n" +
	"\tdownloads\x18\a \x01(\x03R\tdownloads2\xe1\x04\n" +
	"\vFileService\x12F\n" +
	"\tListFiles\x12\x1a.syncreve.ListFilesRequest\x1a\x1b.syncreve.ListFilesResponse\"\x00\x12I\n" +
	"\vGetFileInfo\x12\x1c.syncreve.GetFileInfoRequest\x1a\x1a.syncreve.FileInfoResponse\"\x00\x12G\n" +
	"\n" +
	"CreateFile\x12\x1b.syncreve.CreateFileRequest\x1a\x1a.syncreve.FileInfoResponse\"\x00\x12L\n" +
	"\vDeleteFiles\x12\x1c.syncreve.DeleteFilesRequest\x1a\x1d.syncreve.DeleteFilesResponse\"\x00\x12G\n" +
	"\n" +
	"RenameFile\x12\x1b.syncreve.RenameFileRequest\x1a\x1a.syncreve.FileInfoResponse\"\x00\x12F\n" +
	"\tMoveFiles\x12\x1a.syncreve.MoveFilesRequest\x1a\x1b.syncreve.MoveFilesResponse\"\x00\x12F\n" +
	"\n" +
	"GetFileURL\x12\x1b.syncreve.GetFileURLRequest\x1a\x19.syncreve.FileURLResponse\"\x00\x12O\n" +
	"\rGetDirectLink\x12\x1e.syncreve.GetDirectLinkRequest\x1a\x1c.syncreve.DirectLinkResponse\"\x00B+Z)github.com/xkeyC/Syncreve/pkg/grpc/protosb\x06proto3"

var (
	file_pkg_grpc_protos_file_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_protos_file_service_proto_rawDescData []byte
)

func file_pkg_grpc_protos_file_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protos_file_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protos_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_file_service_proto_rawDesc), len(file_pkg_grpc_protos_file_service_proto_rawDesc)))
	})
	return file_pkg_grpc_protos_file_service_proto_rawDescData
}

var file_pkg_grpc_protos_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_grpc_protos_file_service_proto_goTypes = []any{
	(*ListFilesRequest)(nil),     // 0: syncreve.ListFilesRequest
	(*ListFilesResponse)(nil),    // 1: syncreve.ListFilesResponse
	(*FileInfo)(nil),             // 2: syncreve.FileInfo
	(*GetFileInfoRequest)(nil),   // 3: syncreve.GetFileInfoRequest
	(*FileInfoResponse)(nil),     // 4: syncreve.FileInfoResponse
	(*CreateFileRequest)(nil),    // 5: syncreve.CreateFileRequest
	(*DeleteFilesRequest)(nil),   // 6: syncreve.DeleteFilesRequest
	(*DeleteFilesResponse)(nil),  // 7: syncreve.DeleteFilesResponse
	(*RenameFileRequest)(nil),    // 8: syncreve.RenameFileRequest
	(*MoveFilesRequest)(nil),     // 9: syncreve.MoveFilesRequest
	(*MoveFilesResponse)(nil),    // 10: syncreve.MoveFilesResponse
	(*GetFileURLRequest)(nil),    // 11: syncreve.GetFileURLRequest
	(*FileURLResponse)(nil),      // 12: syncreve.FileURLResponse
	(*GetDirectLinkRequest)(nil), // 13: syncreve.GetDirectLinkRequest
	(*DirectLinkResponse)(nil),   // 14: syncreve.DirectLinkResponse
	(*DirectLink)(nil),           // 15: syncreve.DirectLink
}
var file_pkg_grpc_protos_file_service_proto_depIdxs = []int32{
	2,  // 0: syncreve.ListFilesResponse.files:type_name -> syncreve.FileInfo
	2,  // 1: syncreve.FileInfoResponse.file:type_name -> syncreve.FileInfo
	15, // 2: syncreve.DirectLinkResponse.links:type_name -> syncreve.DirectLink
	0,  // 3: syncreve.FileService.ListFiles:input_type -> syncreve.ListFilesRequest
	3,  // 4: syncreve.FileService.GetFileInfo:input_type -> syncreve.GetFileInfoRequest
	5,  // 5: syncreve.FileService.CreateFile:input_type -> syncreve.CreateFileRequest
	6,  // 6: syncreve.FileService.DeleteFiles:input_type -> syncreve.DeleteFilesRequest
	8,  // 7: syncreve.FileService.RenameFile:input_type -> syncreve.RenameFileRequest
	9,  // 8: syncreve.FileService.MoveFiles:input_type -> syncreve.MoveFilesRequest
	11, // 9: syncreve.FileService.GetFileURL:input_type -> syncreve.GetFileURLRequest
	13, // 10: syncreve.FileService.GetDirectLink:input_type -> syncreve.GetDirectLinkRequest
	1,  // 11: syncreve.FileService.ListFiles:output_type -> syncreve.ListFilesResponse
	4,  // 12: syncreve.FileService.GetFileInfo:output_type -> syncreve.FileInfoResponse
	4,  // 13: syncreve.FileService.CreateFile:output_type -> syncreve.FileInfoResponse
	7,  // 14: syncreve.FileService.DeleteFiles:output_type -> syncreve.DeleteFilesResponse
	4,  // 15: syncreve.FileService.RenameFile:output_type -> syncreve.FileInfoResponse
	10, // 16: syncreve.FileService.MoveFiles:output_type -> syncreve.MoveFilesResponse
	12, // 17: syncreve.FileService.GetFileURL:output_type -> syncreve.FileURLResponse
	14, // 18: syncreve.FileService.GetDirectLink:output_type -> syncreve.DirectLinkResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protos_file_service_proto_init() }
func file_pkg_grpc_protos_file_service_proto_init() {
	if File_pkg_grpc_protos_file_service_proto != nil {
		return
	}
	file_pkg_grpc_protos_file_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_grpc_protos_file_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_grpc_protos_file_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_grpc_protos_file_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_grpc_protos_file_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_pkg_grpc_protos_file_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_pkg_grpc_protos_file_service_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_file_service_proto_rawDesc), len(file_pkg_grpc_protos_file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_protos_file_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protos_file_service_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_protos_file_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protos_file_service_proto = out.File
	file_pkg_grpc_protos_file_service_proto_goTypes = nil
	file_pkg_grpc_protos_file_service_proto_depIdxs = nil
}
