// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/grpc/protos/ping_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pkg_grpc_protos_ping_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_ping_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_ping_service_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pkg_grpc_protos_ping_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_ping_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_ping_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_pkg_grpc_protos_ping_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_protos_ping_service_proto_rawDesc = "" +
	"\n" +
	"\"pkg/grpc/protos/ping_service.proto\x12\bsyncreve\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp2F\n" +
	"\vPingService\x127\n" +
	"\x04Ping\x12\x15.syncreve.PingRequest\x1a\x16.syncreve.PingResponse\"\x00B+Z)github.com/xkeyC/Syncreve/pkg/grpc/protosb\x06proto3"

var (
	file_pkg_grpc_protos_ping_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_protos_ping_service_proto_rawDescData []byte
)

func file_pkg_grpc_protos_ping_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protos_ping_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protos_ping_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_ping_service_proto_rawDesc), len(file_pkg_grpc_protos_ping_service_proto_rawDesc)))
	})
	return file_pkg_grpc_protos_ping_service_proto_rawDescData
}

var file_pkg_grpc_protos_ping_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_protos_ping_service_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: syncreve.PingRequest
	(*PingResponse)(nil), // 1: syncreve.PingResponse
}
var file_pkg_grpc_protos_ping_service_proto_depIdxs = []int32{
	0, // 0: syncreve.PingService.Ping:input_type -> syncreve.PingRequest
	1, // 1: syncreve.PingService.Ping:output_type -> syncreve.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protos_ping_service_proto_init() }
func file_pkg_grpc_protos_ping_service_proto_init() {
	if File_pkg_grpc_protos_ping_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_ping_service_proto_rawDesc), len(file_pkg_grpc_protos_ping_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_protos_ping_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protos_ping_service_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_protos_ping_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protos_ping_service_proto = out.File
	file_pkg_grpc_protos_ping_service_proto_goTypes = nil
	file_pkg_grpc_protos_ping_service_proto_depIdxs = nil
}
