// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/grpc/protos/upload_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadTaskStatus int32

const (
	UploadTaskStatus_UPLOAD_WAITING   UploadTaskStatus = 0
	UploadTaskStatus_UPLOADING        UploadTaskStatus = 1
	UploadTaskStatus_UPLOAD_PAUSED    UploadTaskStatus = 2
	UploadTaskStatus_UPLOAD_COMPLETED UploadTaskStatus = 3
	UploadTaskStatus_UPLOAD_FAILED    UploadTaskStatus = 4
	UploadTaskStatus_UPLOAD_CANCELLED UploadTaskStatus = 5
)

// Enum value maps for UploadTaskStatus.
var (
	UploadTaskStatus_name = map[int32]string{
		0: "UPLOAD_WAITING",
		1: "UPLOADING",
		2: "UPLOAD_PAUSED",
		3: "UPLOAD_COMPLETED",
		4: "UPLOAD_FAILED",
		5: "UPLOAD_CANCELLED",
	}
	UploadTaskStatus_value = map[string]int32{
		"UPLOAD_WAITING":   0,
		"UPLOADING":        1,
		"UPLOAD_PAUSED":    2,
		"UPLOAD_COMPLETED": 3,
		"UPLOAD_FAILED":    4,
		"UPLOAD_CANCELLED": 5,
	}
)

func (x UploadTaskStatus) Enum() *UploadTaskStatus {
	p := new(UploadTaskStatus)
	*p = x
	return p
}

func (x UploadTaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UploadTaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_protos_upload_service_proto_enumTypes[0].Descriptor()
}

func (UploadTaskStatus) Type() protoreflect.EnumType {
	return &file_pkg_grpc_protos_upload_service_proto_enumTypes[0]
}

func (x UploadTaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UploadTaskStatus.Descriptor instead.
func (UploadTaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{0}
}

type UploadTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LocalPath     string                 `protobuf:"bytes,3,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath    string                 `protobuf:"bytes,4,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	TotalSize     int64                  `protobuf:"varint,6,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	UploadedSize  int64                  `protobuf:"varint,7,opt,name=uploaded_size,json=uploadedSize,proto3" json:"uploaded_size,omitempty"`
	Status        UploadTaskStatus       `protobuf:"varint,8,opt,name=status,proto3,enum=syncreve.UploadTaskStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt   *string                `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Speed         *float64               `protobuf:"fixed64,13,opt,name=speed,proto3,oneof" json:"speed,omitempty"`       // bytes per second
	Progress      *float64               `protobuf:"fixed64,14,opt,name=progress,proto3,oneof" json:"progress,omitempty"` // 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskInfo) Reset() {
	*x = UploadTaskInfo{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskInfo) ProtoMessage() {}

func (x *UploadTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskInfo.ProtoReflect.Descriptor instead.
func (*UploadTaskInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadTaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadTaskInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UploadTaskInfo) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadTaskInfo) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *UploadTaskInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadTaskInfo) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadTaskInfo) GetUploadedSize() int64 {
	if x != nil {
		return x.UploadedSize
	}
	return 0
}

func (x *UploadTaskInfo) GetStatus() UploadTaskStatus {
	if x != nil {
		return x.Status
	}
	return UploadTaskStatus_UPLOAD_WAITING
}

func (x *UploadTaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadTaskInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UploadTaskInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UploadTaskInfo) GetCompletedAt() string {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return ""
}

func (x *UploadTaskInfo) GetSpeed() float64 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *UploadTaskInfo) GetProgress() float64 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

type AddUploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath    string                 `protobuf:"bytes,3,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	Overwrite     *bool                  `protobuf:"varint,4,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUploadTaskRequest) Reset() {
	*x = AddUploadTaskRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUploadTaskRequest) ProtoMessage() {}

func (x *AddUploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUploadTaskRequest.ProtoReflect.Descriptor instead.
func (*AddUploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddUploadTaskRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddUploadTaskRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *AddUploadTaskRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *AddUploadTaskRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

type AddBatchUploadTasksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Files          []*UploadFileInfo      `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	RemoteBasePath string                 `protobuf:"bytes,3,opt,name=remote_base_path,json=remoteBasePath,proto3" json:"remote_base_path,omitempty"`
	Overwrite      *bool                  `protobuf:"varint,4,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddBatchUploadTasksRequest) Reset() {
	*x = AddBatchUploadTasksRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBatchUploadTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBatchUploadTasksRequest) ProtoMessage() {}

func (x *AddBatchUploadTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBatchUploadTasksRequest.ProtoReflect.Descriptor instead.
func (*AddBatchUploadTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddBatchUploadTasksRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddBatchUploadTasksRequest) GetFiles() []*UploadFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *AddBatchUploadTasksRequest) GetRemoteBasePath() string {
	if x != nil {
		return x.RemoteBasePath
	}
	return ""
}

func (x *AddBatchUploadTasksRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

type UploadFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RelativePath  *string                `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3,oneof" json:"relative_path,omitempty"` // relative to base path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileInfo) Reset() {
	*x = UploadFileInfo{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileInfo) ProtoMessage() {}

func (x *UploadFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileInfo.ProtoReflect.Descriptor instead.
func (*UploadFileInfo) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{3}
}

func (x *UploadFileInfo) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadFileInfo) GetRelativePath() string {
	if x != nil && x.RelativePath != nil {
		return *x.RelativePath
	}
	return ""
}

type AddUploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUploadTaskResponse) Reset() {
	*x = AddUploadTaskResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUploadTaskResponse) ProtoMessage() {}

func (x *AddUploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUploadTaskResponse.ProtoReflect.Descriptor instead.
func (*AddUploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddUploadTaskResponse) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

type CancelUploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUploadTaskRequest) Reset() {
	*x = CancelUploadTaskRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUploadTaskRequest) ProtoMessage() {}

func (x *CancelUploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUploadTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelUploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{5}
}

func (x *CancelUploadTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelUploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelUploadTaskResponse) Reset() {
	*x = CancelUploadTaskResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelUploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelUploadTaskResponse) ProtoMessage() {}

func (x *CancelUploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelUploadTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelUploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelUploadTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelUploadTaskResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetUploadTaskInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadTaskInfoRequest) Reset() {
	*x = GetUploadTaskInfoRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTaskInfoRequest) ProtoMessage() {}

func (x *GetUploadTaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTaskInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUploadTaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetUploadTaskInfoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type UploadTaskInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *UploadTaskInfo        `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskInfoResponse) Reset() {
	*x = UploadTaskInfoResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskInfoResponse) ProtoMessage() {}

func (x *UploadTaskInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskInfoResponse.ProtoReflect.Descriptor instead.
func (*UploadTaskInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{8}
}

func (x *UploadTaskInfoResponse) GetTask() *UploadTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListUploadTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        *UploadTaskStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=syncreve.UploadTaskStatus,oneof" json:"status,omitempty"`
	Page          *int32                 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PerPage       *int32                 `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3,oneof" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUploadTasksRequest) Reset() {
	*x = ListUploadTasksRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUploadTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUploadTasksRequest) ProtoMessage() {}

func (x *ListUploadTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUploadTasksRequest.ProtoReflect.Descriptor instead.
func (*ListUploadTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListUploadTasksRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListUploadTasksRequest) GetStatus() UploadTaskStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UploadTaskStatus_UPLOAD_WAITING
}

func (x *ListUploadTasksRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListUploadTasksRequest) GetPerPage() int32 {
	if x != nil && x.PerPage != nil {
		return *x.PerPage
	}
	return 0
}

type ListUploadTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*UploadTaskInfo      `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUploadTasksResponse) Reset() {
	*x = ListUploadTasksResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUploadTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUploadTasksResponse) ProtoMessage() {}

func (x *ListUploadTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUploadTasksResponse.ProtoReflect.Descriptor instead.
func (*ListUploadTasksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListUploadTasksResponse) GetTasks() []*UploadTaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListUploadTasksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WatchUploadTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        *string                `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3,oneof" json:"task_id,omitempty"` // If not set, watch all tasks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchUploadTaskStatusRequest) Reset() {
	*x = WatchUploadTaskStatusRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchUploadTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchUploadTaskStatusRequest) ProtoMessage() {}

func (x *WatchUploadTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchUploadTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchUploadTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{11}
}

func (x *WatchUploadTaskStatusRequest) GetTaskId() string {
	if x != nil && x.TaskId != nil {
		return *x.TaskId
	}
	return ""
}

type UploadTaskStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *UploadTaskInfo        `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskStatusUpdate) Reset() {
	*x = UploadTaskStatusUpdate{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskStatusUpdate) ProtoMessage() {}

func (x *UploadTaskStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskStatusUpdate.ProtoReflect.Descriptor instead.
func (*UploadTaskStatusUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{12}
}

func (x *UploadTaskStatusUpdate) GetTask() *UploadTaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

type PauseUploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseUploadTaskRequest) Reset() {
	*x = PauseUploadTaskRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseUploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseUploadTaskRequest) ProtoMessage() {}

func (x *PauseUploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseUploadTaskRequest.ProtoReflect.Descriptor instead.
func (*PauseUploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{13}
}

func (x *PauseUploadTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type PauseUploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseUploadTaskResponse) Reset() {
	*x = PauseUploadTaskResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseUploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseUploadTaskResponse) ProtoMessage() {}

func (x *PauseUploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseUploadTaskResponse.ProtoReflect.Descriptor instead.
func (*PauseUploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{14}
}

func (x *PauseUploadTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResumeUploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeUploadTaskRequest) Reset() {
	*x = ResumeUploadTaskRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeUploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeUploadTaskRequest) ProtoMessage() {}

func (x *ResumeUploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeUploadTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeUploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResumeUploadTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ResumeUploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeUploadTaskResponse) Reset() {
	*x = ResumeUploadTaskResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeUploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeUploadTaskResponse) ProtoMessage() {}

func (x *ResumeUploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeUploadTaskResponse.ProtoReflect.Descriptor instead.
func (*ResumeUploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeUploadTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetryUploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryUploadTaskRequest) Reset() {
	*x = RetryUploadTaskRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryUploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryUploadTaskRequest) ProtoMessage() {}

func (x *RetryUploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryUploadTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryUploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{17}
}

func (x *RetryUploadTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RetryUploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewTaskId     *string                `protobuf:"bytes,2,opt,name=new_task_id,json=newTaskId,proto3,oneof" json:"new_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryUploadTaskResponse) Reset() {
	*x = RetryUploadTaskResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryUploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryUploadTaskResponse) ProtoMessage() {}

func (x *RetryUploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryUploadTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryUploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{18}
}

func (x *RetryUploadTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryUploadTaskResponse) GetNewTaskId() string {
	if x != nil && x.NewTaskId != nil {
		return *x.NewTaskId
	}
	return ""
}

type ClearUploadCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUploadCompletedRequest) Reset() {
	*x = ClearUploadCompletedRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUploadCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUploadCompletedRequest) ProtoMessage() {}

func (x *ClearUploadCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUploadCompletedRequest.ProtoReflect.Descriptor instead.
func (*ClearUploadCompletedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{19}
}

func (x *ClearUploadCompletedRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ClearUploadCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearedCount  int32                  `protobuf:"varint,1,opt,name=cleared_count,json=clearedCount,proto3" json:"cleared_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUploadCompletedResponse) Reset() {
	*x = ClearUploadCompletedResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUploadCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUploadCompletedResponse) ProtoMessage() {}

func (x *ClearUploadCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUploadCompletedResponse.ProtoReflect.Descriptor instead.
func (*ClearUploadCompletedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{20}
}

func (x *ClearUploadCompletedResponse) GetClearedCount() int32 {
	if x != nil {
		return x.ClearedCount
	}
	return 0
}

type GetUploadStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatsRequest) Reset() {
	*x = GetUploadStatsRequest{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatsRequest) ProtoMessage() {}

func (x *GetUploadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUploadStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetUploadStatsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type UploadStatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks        int64                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	WaitingTasks      int64                  `protobuf:"varint,2,opt,name=waiting_tasks,json=waitingTasks,proto3" json:"waiting_tasks,omitempty"`
	UploadingTasks    int64                  `protobuf:"varint,3,opt,name=uploading_tasks,json=uploadingTasks,proto3" json:"uploading_tasks,omitempty"`
	CompletedTasks    int64                  `protobuf:"varint,4,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	FailedTasks       int64                  `protobuf:"varint,5,opt,name=failed_tasks,json=failedTasks,proto3" json:"failed_tasks,omitempty"`
	TotalUploadedSize float64                `protobuf:"fixed64,6,opt,name=total_uploaded_size,json=totalUploadedSize,proto3" json:"total_uploaded_size,omitempty"`
	CurrentSpeed      float64                `protobuf:"fixed64,7,opt,name=current_speed,json=currentSpeed,proto3" json:"current_speed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UploadStatsResponse) Reset() {
	*x = UploadStatsResponse{}
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatsResponse) ProtoMessage() {}

func (x *UploadStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_protos_upload_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatsResponse.ProtoReflect.Descriptor instead.
func (*UploadStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_protos_upload_service_proto_rawDescGZIP(), []int{22}
}

func (x *UploadStatsResponse) GetTotalTasks() int64 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *UploadStatsResponse) GetWaitingTasks() int64 {
	if x != nil {
		return x.WaitingTasks
	}
	return 0
}

func (x *UploadStatsResponse) GetUploadingTasks() int64 {
	if x != nil {
		return x.UploadingTasks
	}
	return 0
}

func (x *UploadStatsResponse) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *UploadStatsResponse) GetFailedTasks() int64 {
	if x != nil {
		return x.FailedTasks
	}
	return 0
}

func (x *UploadStatsResponse) GetTotalUploadedSize() float64 {
	if x != nil {
		return x.TotalUploadedSize
	}
	return 0
}

func (x *UploadStatsResponse) GetCurrentSpeed() float64 {
	if x != nil {
		return x.CurrentSpeed
	}
	return 0
}

var File_pkg_grpc_protos_upload_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_protos_upload_service_proto_rawDesc = "" +
	"\n" +
	"$pkg/grpc/protos/upload_service.proto\x12\bsyncreve\"\xf4\x03\n" +
	"\x0eUploadTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"local_path\x18\x03 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x04 \x01(\tR\n" +
	"remotePath\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"total_size\x18\x06 \x01(\x03R\ttotalSize\x12#\n" +
	"\ruploaded_size\x18\a \x01(\x03R\fuploadedSize\x122\n" +
	"\x06status\x18\b \x01(\x0e2\x1a.syncreve.UploadTaskStatusR\x06status\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12&\n" +
	"\fcompleted_at\x18\f \x01(\tH\x00R\vcompletedAt\x88\x01\x01\x12\x19\n" +
	"\x05speed\x18\r \x01(\x01H\x01R\x05speed\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x0e \x01(\x01H\x02R\bprogress\x88\x01\x01B\x0f\n" +
	"\r_completed_atB\b\n" +
	"\x06_speedB\v\n" +
	"\t_progress\"\xa6\x01\n" +
	"\x14AddUploadTaskRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x03 \x01(\tR\n" +
	"remotePath\x12!\n" +
	"\toverwrite\x18\x04 \x01(\bH\x00R\toverwrite\x88\x01\x01B\f\n" +
	"\n" +
	"_overwrite\"\xc6\x01\n" +
	"\x1aAddBatchUploadTasksRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12.\n" +
	"\x05files\x18\x02 \x03(\v2\x18.syncreve.UploadFileInfoR\x05files\x12(\n" +
	"\x10remote_base_path\x18\x03 \x01(\tR\x0eremoteBasePath\x12!\n" +
	"\toverwrite\x18\x04 \x01(\bH\x00R\toverwrite\x88\x01\x01B\f\n" +
	"\n" +
	"_overwrite\"k\n" +
	"\x0eUploadFileInfo\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12(\n" +
	"\rrelative_path\x18\x02 \x01(\tH\x00R\frelativePath\x88\x01\x01B\x10\n" +
	"\x0e_relative_path\"2\n" +
	"\x15AddUploadTaskResponse\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\"2\n" +
	"\x17CancelUploadTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"Y\n" +
	"\x18CancelUploadTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"3\n" +
	"\x18GetUploadTaskInfoRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"F\n" +
	"\x16UploadTaskInfoResponse\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\x18.syncreve.UploadTaskInfoR\x04task\"\xca\x01\n" +
	"\x16ListUploadTasksRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.syncreve.UploadTaskStatusH\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05H\x01R\x04page\x88\x01\x01\x12\x1e\n" +
	"\bper_page\x18\x04 \x01(\x05H\x02R\aperPage\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_pageB\v\n" +
	"\t_per_page\"_\n" +
	"\x17ListUploadTasksResponse\x12.\n" +
	"\x05tasks\x18\x01 \x03(\v2\x18.syncreve.UploadTaskInfoR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"H\n" +
	"\x1cWatchUploadTaskStatusRequest\x12\x1c\n" +
	"\atask_id\x18\x01 \x01(\tH\x00R\x06taskId\x88\x01\x01B\n" +
	"\n" +
	"\b_task_id\"F\n" +
	"\x16UploadTaskStatusUpdate\x12,\n" +
	"\x04task\x18\x01 \x01(\v2\x18.syncreve.UploadTaskInfoR\x04task\"1\n" +
	"\x16PauseUploadTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"3\n" +
	"\x17PauseUploadTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x17ResumeUploadTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"4\n" +
	"\x18ResumeUploadTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x16RetryUploadTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"h\n" +
	"\x17RetryUploadTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\vnew_task_id\x18\x02 \x01(\tH\x00R\tnewTaskId\x88\x01\x01B\x0e\n" +
	"\f_new_task_id\"<\n" +
	"\x1bClearUploadCompletedRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"C\n" +
	"\x1cClearUploadCompletedResponse\x12#\n" +
	"\rcleared_count\x18\x01 \x01(\x05R\fclearedCount\"6\n" +
	"\x15GetUploadStatsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xa5\x02\n" +
	"\x13UploadStatsResponse\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x03R\n" +
	"totalTasks\x12#\n" +
	"\rwaiting_tasks\x18\x02 \x01(\x03R\fwaitingTasks\x12'\n" +
	"\x0fuploading_tasks\x18\x03 \x01(\x03R\x0euploadingTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x04 \x01(\x03R\x0ecompletedTasks\x12!\n" +
	"\ffailed_tasks\x18\x05 \x01(\x03R\vfailedTasks\x12.\n" +
	"\x13total_uploaded_size\x18\x06 \x01(\x01R\x11totalUploadedSize\x12#\n" +
	"\rcurrent_speed\x18\a \x01(\x01R\fcurrentSpeed*\x87\x01\n" +
	"\x10UploadTaskStatus\x12\x12\n" +
	"\x0eUPLOAD_WAITING\x10\x00\x12\r\n" +
	"\tUPLOADING\x10\x01\x12\x11\n" +
	"\rUPLOAD_PAUSED\x10\x02\x12\x14\n" +
	"\x10UPLOAD_COMPLETED\x10\x03\x12\x11\n" +
	"\rUPLOAD_FAILED\x10\x04\x12\x14\n" +
	"\x10UPLOAD_CANCELLED\x10\x052\xca\a\n" +
	"\rUploadService\x12L\n" +
	"\aAddTask\x12\x1e.syncreve.AddUploadTaskRequest\x1a\x1f.syncreve.AddUploadTaskResponse\"\x00\x12X\n" +
	"\rAddBatchTasks\x12$.syncreve.AddBatchUploadTasksRequest\x1a\x1f.syncreve.AddUploadTaskResponse\"\x00\x12U\n" +
	"\n" +
	"CancelTask\x12!.syncreve.CancelUploadTaskRequest\x1a\".syncreve.CancelUploadTaskResponse\"\x00\x12U\n" +
	"\vGetTaskInfo\x12\".syncreve.GetUploadTaskInfoRequest\x1a .syncreve.UploadTaskInfoResponse\"\x00\x12R\n" +
	"\tListTasks\x12 .syncreve.ListUploadTasksRequest\x1a!.syncreve.ListUploadTasksResponse\"\x00\x12_\n" +
	"\x0fWatchTaskStatus\x12&.syncreve.WatchUploadTaskStatusRequest\x1a .syncreve.UploadTaskStatusUpdate\"\x000\x01\x12R\n" +
	"\tPauseTask\x12 .syncreve.PauseUploadTaskRequest\x1a!.syncreve.PauseUploadTaskResponse\"\x00\x12U\n" +
	"\n" +
	"ResumeTask\x12!.syncreve.ResumeUploadTaskRequest\x1a\".syncreve.ResumeUploadTaskResponse\"\x00\x12R\n" +
	"\tRetryTask\x12 .syncreve.RetryUploadTaskRequest\x1a!.syncreve.RetryUploadTaskResponse\"\x00\x12a\n" +
	"\x0eClearCompleted\x12%.syncreve.ClearUploadCompletedRequest\x1a&.syncreve.ClearUploadCompletedResponse\"\x00\x12L\n" +
	"\bGetStats\x12\x1f.syncreve.GetUploadStatsRequest\x1a\x1d.syncreve.UploadStatsResponse\"\x00B+Z)github.com/xkeyC/Syncreve/pkg/grpc/protosb\x06proto3"

var (
	file_pkg_grpc_protos_upload_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_protos_upload_service_proto_rawDescData []byte
)

func file_pkg_grpc_protos_upload_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_protos_upload_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_protos_upload_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_upload_service_proto_rawDesc), len(file_pkg_grpc_protos_upload_service_proto_rawDesc)))
	})
	return file_pkg_grpc_protos_upload_service_proto_rawDescData
}

var file_pkg_grpc_protos_upload_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_grpc_protos_upload_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_grpc_protos_upload_service_proto_goTypes = []any{
	(UploadTaskStatus)(0),                // 0: syncreve.UploadTaskStatus
	(*UploadTaskInfo)(nil),               // 1: syncreve.UploadTaskInfo
	(*AddUploadTaskRequest)(nil),         // 2: syncreve.AddUploadTaskRequest
	(*AddBatchUploadTasksRequest)(nil),   // 3: syncreve.AddBatchUploadTasksRequest
	(*UploadFileInfo)(nil),               // 4: syncreve.UploadFileInfo
	(*AddUploadTaskResponse)(nil),        // 5: syncreve.AddUploadTaskResponse
	(*CancelUploadTaskRequest)(nil),      // 6: syncreve.CancelUploadTaskRequest
	(*CancelUploadTaskResponse)(nil),     // 7: syncreve.CancelUploadTaskResponse
	(*GetUploadTaskInfoRequest)(nil),     // 8: syncreve.GetUploadTaskInfoRequest
	(*UploadTaskInfoResponse)(nil),       // 9: syncreve.UploadTaskInfoResponse
	(*ListUploadTasksRequest)(nil),       // 10: syncreve.ListUploadTasksRequest
	(*ListUploadTasksResponse)(nil),      // 11: syncreve.ListUploadTasksResponse
	(*WatchUploadTaskStatusRequest)(nil), // 12: syncreve.WatchUploadTaskStatusRequest
	(*UploadTaskStatusUpdate)(nil),       // 13: syncreve.UploadTaskStatusUpdate
	(*PauseUploadTaskRequest)(nil),       // 14: syncreve.PauseUploadTaskRequest
	(*PauseUploadTaskResponse)(nil),      // 15: syncreve.PauseUploadTaskResponse
	(*ResumeUploadTaskRequest)(nil),      // 16: syncreve.ResumeUploadTaskRequest
	(*ResumeUploadTaskResponse)(nil),     // 17: syncreve.ResumeUploadTaskResponse
	(*RetryUploadTaskRequest)(nil),       // 18: syncreve.RetryUploadTaskRequest
	(*RetryUploadTaskResponse)(nil),      // 19: syncreve.RetryUploadTaskResponse
	(*ClearUploadCompletedRequest)(nil),  // 20: syncreve.ClearUploadCompletedRequest
	(*ClearUploadCompletedResponse)(nil), // 21: syncreve.ClearUploadCompletedResponse
	(*GetUploadStatsRequest)(nil),        // 22: syncreve.GetUploadStatsRequest
	(*UploadStatsResponse)(nil),          // 23: syncreve.UploadStatsResponse
}
var file_pkg_grpc_protos_upload_service_proto_depIdxs = []int32{
	0,  // 0: syncreve.UploadTaskInfo.status:type_name -> syncreve.UploadTaskStatus
	4,  // 1: syncreve.AddBatchUploadTasksRequest.files:type_name -> syncreve.UploadFileInfo
	1,  // 2: syncreve.UploadTaskInfoResponse.task:type_name -> syncreve.UploadTaskInfo
	0,  // 3: syncreve.ListUploadTasksRequest.status:type_name -> syncreve.UploadTaskStatus
	1,  // 4: syncreve.ListUploadTasksResponse.tasks:type_name -> syncreve.UploadTaskInfo
	1,  // 5: syncreve.UploadTaskStatusUpdate.task:type_name -> syncreve.UploadTaskInfo
	2,  // 6: syncreve.UploadService.AddTask:input_type -> syncreve.AddUploadTaskRequest
	3,  // 7: syncreve.UploadService.AddBatchTasks:input_type -> syncreve.AddBatchUploadTasksRequest
	6,  // 8: syncreve.UploadService.CancelTask:input_type -> syncreve.CancelUploadTaskRequest
	8,  // 9: syncreve.UploadService.GetTaskInfo:input_type -> syncreve.GetUploadTaskInfoRequest
	10, // 10: syncreve.UploadService.ListTasks:input_type -> syncreve.ListUploadTasksRequest
	12, // 11: syncreve.UploadService.WatchTaskStatus:input_type -> syncreve.WatchUploadTaskStatusRequest
	14, // 12: syncreve.UploadService.PauseTask:input_type -> syncreve.PauseUploadTaskRequest
	16, // 13: syncreve.UploadService.ResumeTask:input_type -> syncreve.ResumeUploadTaskRequest
	18, // 14: syncreve.UploadService.RetryTask:input_type -> syncreve.RetryUploadTaskRequest
	20, // 15: syncreve.UploadService.ClearCompleted:input_type -> syncreve.ClearUploadCompletedRequest
	22, // 16: syncreve.UploadService.GetStats:input_type -> syncreve.GetUploadStatsRequest
	5,  // 17: syncreve.UploadService.AddTask:output_type -> syncreve.AddUploadTaskResponse
	5,  // 18: syncreve.UploadService.AddBatchTasks:output_type -> syncreve.AddUploadTaskResponse
	7,  // 19: syncreve.UploadService.CancelTask:output_type -> syncreve.CancelUploadTaskResponse
	9,  // 20: syncreve.UploadService.GetTaskInfo:output_type -> syncreve.UploadTaskInfoResponse
	11, // 21: syncreve.UploadService.ListTasks:output_type -> syncreve.ListUploadTasksResponse
	13, // 22: syncreve.UploadService.WatchTaskStatus:output_type -> syncreve.UploadTaskStatusUpdate
	15, // 23: syncreve.UploadService.PauseTask:output_type -> syncreve.PauseUploadTaskResponse
	17, // 24: syncreve.UploadService.ResumeTask:output_type -> syncreve.ResumeUploadTaskResponse
	19, // 25: syncreve.UploadService.RetryTask:output_type -> syncreve.RetryUploadTaskResponse
	21, // 26: syncreve.UploadService.ClearCompleted:output_type -> syncreve.ClearUploadCompletedResponse
	23, // 27: syncreve.UploadService.GetStats:output_type -> syncreve.UploadStatsResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_grpc_protos_upload_service_proto_init() }
func file_pkg_grpc_protos_upload_service_proto_init() {
	if File_pkg_grpc_protos_upload_service_proto != nil {
		return
	}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_pkg_grpc_protos_upload_service_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_protos_upload_service_proto_rawDesc), len(file_pkg_grpc_protos_upload_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_protos_upload_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_protos_upload_service_proto_depIdxs,
		EnumInfos:         file_pkg_grpc_protos_upload_service_proto_enumTypes,
		MessageInfos:      file_pkg_grpc_protos_upload_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_protos_upload_service_proto = out.File
	file_pkg_grpc_protos_upload_service_proto_goTypes = nil
	file_pkg_grpc_protos_upload_service_proto_depIdxs = nil
}
